# =============================================================================
# BLASTOISE Development Environment (environment.yaml)
# =============================================================================
# 
# This file defines a conda/mamba environment specification for the BLASTOISE
# project. It specifies the exact dependencies and versions needed to create
# a reproducible development and runtime environment.
#
# BLASTOISE is a bioinformatics tool for identifying SIDER repetitive 
# elements in Leishmania genomic data using BLAST-based approaches.
#
# Usage:
#   conda env create -f environment.yaml
#   conda activate blastoise
#
# Or with mamba (faster):
#   mamba env create -f environment.yaml
#   mamba activate blastoise
#
# For more information about conda environments, see:
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# =============================================================================

# Environment name (will be used when activating: conda activate blastoise)
name: blastoise

# Conda channels to search for packages (order matters - higher priority first)
channels:
  - conda-forge          # Community-driven collection of conda recipes
  - bioconda             # Bioinformatics-focused conda channel

# Package dependencies - core requirements for BLASTOISE functionality
dependencies:
  - python >=3.12               # Python runtime requirement
  - biopython >=1.85            # Biological computation library
  - blast >=2.12                # NCBI BLAST+ suite for sequence alignment
  - joblib >=1.5.1              # Parallel computing library
  - pandas >=2.3.1              # Data manipulation and analysis
  - pyranges >=0.1.4            # Genomic interval operations
