# =============================================================================
# BLASTOISE Conda Package Recipe (meta.yaml)
# =============================================================================
# 
# This file is a conda recipe specification that defines how to build and 
# package the BLASTOISE software for distribution via conda/mamba package 
# managers. It contains metadata about the package, build instructions, 
# dependencies, tests, and project information.
#
# BLASTOISE is a bioinformatics tool for identifying SIDER repetitive 
# elements in Leishmania genomic data using BLAST-based approaches.
#
# For more information about conda recipes, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
#
# =============================================================================
# DEVELOPER NOTES - BUILDING AND UPLOADING TO ANACONDA CLOUD
# =============================================================================
#
# IMPORTANT: This package requires dependencies from conda-forge and bioconda
# channels that are not available in the default conda channel.
#
# --- HOW TO BUILD THE PACKAGE ---
# The following channels MUST be specified during build:
#   conda-build meta.yaml -c conda-forge -c bioconda
#
# --- HOW TO UPLOAD TO ANACONDA CLOUD ---
# Option 1 - Build and upload in one step:
#   conda-build meta.yaml -c conda-forge -c bioconda --upload
#
# Option 2 - Build first, then upload separately:
#   conda-build meta.yaml -c conda-forge -c bioconda
#   anaconda upload /path/to/built/package.tar.bz2
#
# --- PACKAGE INSTALLATION FOR USERS ---
# Users need to specify the same channels when installing:
#   conda install -c rfpacheco -c conda-forge -c bioconda blastoise
#
# --- OPTIONAL: Global channel configuration ---
# To avoid specifying channels every time, create ~/.condarc:
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#
# Note: The "channels" section cannot be added directly to this meta.yaml file
# as it's not a standard conda-build feature. Channels must be specified at
# build time via command line arguments.
#
# =============================================================================

# Package identification and versioning
package:
  name: blastoise                    # Package name as it appears in conda
  version: "0.4.3"                  # Current version number

# Source code location for building the package
source:
  path: .                           # Build from current directory (local source)

# Build configuration and instructions
build:
  noarch: python                    # Platform-independent Python package
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # Installation command
  entry_points:                     # Command-line executables created
    - blastoise = blastoise.main:main
    - blastoise-sider-filter = blastoise.extra.sider_filter:main

# Package dependencies specification
requirements:
  host:                            # Build-time dependencies (needed during package creation)
    - python 3.12.*               # Minimum Python version required
    - pip                          # Package installer
    - setuptools <81               # Pin to avoid pkg_resources warnings (deprecated versions in PyRagnes)
  run:                             # Runtime dependencies (needed when using the package)
    - python 3.12.*               # Python runtime requirement
    - blast >=2.17.0              # NCBI BLAST+ suite for sequence alignment (from bioconda)
    - biopython >=1.85            # Biological computation library
    - joblib >=1.5.1              # Parallel computing library
    - pandas >=2.3.1              # Data manipulation and analysis
    - pyranges >=0.1.4            # Genomic interval operations (from conda-forge)

# Package testing configuration
test:
  imports:                         # Test that these modules can be imported
    - blastoise
    - blastoise.modules
    - blastoise.extra
  commands:                        # Test that command-line tools work
    - blastoise --help
    - blastoise-sider-filter --help

# Project metadata and documentation links
about:
  home: "https://github.com/rfpacheco/BLASTOISE"           # Project homepage
  license: MIT                                             # Software license
  summary: "A Tool for SIDER Repetitive Sequence Discovery in Genomic Data"
  description: |                                           # Detailed description
    BLASTOISE (BLAST Oriented to the Identification of SIDER Elements) is a Python-based Linux software 
    designed to automate the identification of SIDER elements within Leishmania spp. species. These 
    retroposons, known for their heterogeneity and degeneration, pose significant challenges in their 
    identification, which BLASTOISE effectively addresses.
  doc_url: "https://github.com/rfpacheco/BLASTOISE#readme" # Documentation URL
  dev_url: "https://github.com/rfpacheco/BLASTOISE"        # Development/source URL